# Generated by Django 4.0.4 on 2022-04-14 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='econtact',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='eid',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changerequest',
            name='erequestedby',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='estatus',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='edescription',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='eemail',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='ename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='changerequest',
            table='tbl_changerequest',
        ),
    ]
