# Generated by Django 4.0.4 on 2022-04-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0003_client_rename_edescription_changerequest_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='requestedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esign.client'),
        ),
    ]
